"""refactor_multi_agent_rag_tables

Revision ID: 06086ceb0bfb
Revises: 0d332467b77a
Create Date: 2026-06-24 00:36:06.321157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06086ceb0bfb'
down_revision: Union[str, Sequence[str], None] = '0d332467b77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_message_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_tasks_conversation_id'), 'async_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_async_tasks_user_id'), 'async_tasks', ['user_id'], unique=False)
    
    # 1. 优先解除 file_reports 对 research_sessions 的外键约束绑定，防止 DependentObjectsStillExistError
    op.drop_constraint('file_reports_session_id_fkey', 'file_reports', type_='foreignkey')

    # 2. 干净地删除旧的研究图消息表与会话表
    op.drop_index(op.f('ix_research_messages_session_id'), table_name='research_messages')
    op.drop_table('research_messages')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_table('research_sessions')

    # 3. 对 file_reports 结构进行升级 (在添加 non-nullable 列时加入 server_default 防止旧记录同步失败)
    op.add_column('file_reports', sa.Column('trigger_message_id', sa.BigInteger(), nullable=True))
    op.add_column('file_reports', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.add_column('file_reports', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('file_reports', sa.Column('is_saved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    op.drop_index(op.f('ix_file_reports_session_id'), table_name='file_reports')
    op.create_index(op.f('ix_file_reports_conversation_id'), 'file_reports', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_file_reports_task_id'), 'file_reports', ['task_id'], unique=True)
    
    op.create_foreign_key(None, 'file_reports', 'messages', ['trigger_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'file_reports', 'async_tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'file_reports', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_column('file_reports', 'session_id')

    # 4. 对 messages 结构进行升级 (同样在添加 is_subagent_result non-nullable 列时提供默认值)
    op.add_column('messages', sa.Column('is_subagent_result', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('messages', sa.Column('referred_message_id', sa.BigInteger(), nullable=True))
    op.add_column('messages', sa.Column('associated_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['referred_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'async_tasks', ['associated_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'associated_task_id')
    op.drop_column('messages', 'referred_message_id')
    op.drop_column('messages', 'is_subagent_result')
    op.add_column('file_reports', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_reports', type_='foreignkey')
    op.drop_constraint(None, 'file_reports', type_='foreignkey')
    op.drop_constraint(None, 'file_reports', type_='foreignkey')
    op.create_foreign_key(op.f('file_reports_session_id_fkey'), 'file_reports', 'research_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_file_reports_task_id'), table_name='file_reports')
    op.drop_index(op.f('ix_file_reports_conversation_id'), table_name='file_reports')
    op.create_index(op.f('ix_file_reports_session_id'), 'file_reports', ['session_id'], unique=False)
    op.drop_column('file_reports', 'is_saved')
    op.drop_column('file_reports', 'task_id')
    op.drop_column('file_reports', 'conversation_id')
    op.drop_column('file_reports', 'trigger_message_id')
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('research_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('research_sessions_pkey'))
    )
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('research_messages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attached_file_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_report_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['generated_report_id'], ['file_reports.id'], name=op.f('research_messages_generated_report_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('research_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('research_messages_pkey'))
    )
    op.create_index(op.f('ix_research_messages_session_id'), 'research_messages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_async_tasks_user_id'), table_name='async_tasks')
    op.drop_index(op.f('ix_async_tasks_conversation_id'), table_name='async_tasks')
    op.drop_table('async_tasks')
    # ### end Alembic commands ###
