"""update research tables

Revision ID: 31f84daa4a09
Revises: 6148d55a0dde
Create Date: 2026-06-15 02:00:17.726051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f84daa4a09'
down_revision: Union[str, Sequence[str], None] = '6148d55a0dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('research_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attached_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_report_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_report_id'], ['file_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_messages_session_id'), 'research_messages', ['session_id'], unique=False)
    op.add_column('file_reports', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_file_reports_session_id'), 'file_reports', ['session_id'], unique=False)
    op.create_foreign_key(None, 'file_reports', 'research_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('file_reports', 'query')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('file_reports', sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_reports', type_='foreignkey')
    op.drop_index(op.f('ix_file_reports_session_id'), table_name='file_reports')
    op.drop_column('file_reports', 'session_id')
    op.drop_index(op.f('ix_research_messages_session_id'), table_name='research_messages')
    op.drop_table('research_messages')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    # ### end Alembic commands ###
