"""add_file_document_unique_constraint

Revision ID: 4fa502c18cb8
Revises: 7b89fcdfb297
Create Date: 2026-07-02 23:00:44.128839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa502c18cb8'
down_revision: Union[str, Sequence[str], None] = '7b89fcdfb297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_sha256_uc', 'file_documents', ['user_id', 'sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_sha256_uc', 'file_documents', type_='unique')
    # ### end Alembic commands ###
