"""add full content and lines to files

Revision ID: 6148d55a0dde
Revises: 8f5b19545ee0
Create Date: 2026-06-10 19:40:39.050282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6148d55a0dde'
down_revision: Union[str, Sequence[str], None] = '8f5b19545ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('start_line', sa.BigInteger(), nullable=True))
    op.add_column('file_chunks', sa.Column('end_line', sa.BigInteger(), nullable=True))
    op.add_column('file_documents', sa.Column('full_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_documents', 'full_content')
    op.drop_column('file_chunks', 'end_line')
    op.drop_column('file_chunks', 'start_line')
    # ### end Alembic commands ###
