"""add_users_and_credentials

Revision ID: d73ddba7fcf9
Revises: 50520a5d8e0c
Create Date: 2026-05-28 15:49:02.808529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73ddba7fcf9'
down_revision: Union[str, Sequence[str], None] = '50520a5d8e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier', name='uq_provider_identifier'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_id_provider')
    )
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_table('user_credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
